git_repository(
    name = "org_dropbox_rules_node",
    remote = "https://github.com/dropbox/rules_node.git",
    commit = "master",
)

load("@org_dropbox_rules_node//node:defs.bzl", "node_repositories")
node_repositories()
