git_repository(
    name = "org_dropbox_rules_node",
    remote = "https://github.com/dropbox/rules_node.git",
    commit = "74d8aeb40d079acdceb2380af2a72e29613a8fd6",
)

load("@org_dropbox_rules_node//node:defs.bzl", "node_repositories", "NODEJS_BUILD_FILE_CONTENT")

node_repositories(omit_nodejs=True)

new_http_archive(
    name = "nodejs",
    url = "https://nodejs.org/dist/v8.11.4/node-v8.11.4-linux-x64.tar.gz",
    strip_prefix = "node-v8.11.4-linux-x64",
    sha256 = "c69abe770f002a7415bd00f7ea13b086650c1dd925ef0c3bf8de90eabecc8790",
    build_file_content = NODEJS_BUILD_FILE_CONTENT,
)
